# service gateway
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    gateway: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# service get
apiVersion: v1
kind: Service
metadata:
  name: get-service
spec:
  selector:
    get: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# service post
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    post: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      