# service gateway
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    gateway: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# service get
apiVersion: v1
kind: Service
metadata:
  name: get-service
spec:
  selector:
    get: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

# service post
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    post: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
---

# service post
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  selector:
    nats: go-kubectl-krakend
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
    - protocol: TCP
      port: 6222
      targetPort: 6222
    - protocol: TCP
      port: 8222
      targetPort: 8222
    - protocol: UDP
      port: 4222
      targetPort: 4222
    - protocol: UDP
      port: 6222
      targetPort: 6222
    - protocol: UDP
      port: 8222
      targetPort: 8222
      