name: ci

on:
  push:
    branches:
      - 'master'

env:
  IMAGE_SERVICE_GATEWAY: nugrohosam/go-kubectl-krakend-src-gateway:latest
  IMAGE_SERVICE_POST: nugrohosam/go-kubectl-krakend-src-post:latest
  IMAGE_SERVICE_GET: nugrohosam/go-kubectl-krakend-src-get:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push gateway service
        id: docker_build_gateway
        uses: docker/build-push-action@v2
        with:
          file: ./src/gateway/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_GATEWAY }}
      -
        name: Build and push post
        id: docker_build_post
        uses: docker/build-push-action@v2
        with:
          file: ./src/post/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_POST }}
      -
        name: Build and push get
        id: docker_build_get
        uses: docker/build-push-action@v2
        with:
          file: ./src/get/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_GET }}