name: deploy-docker-post

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/post/**'

env:
  IMAGE_SERVICE_POST: nugrohosam/go-kubectl-krakend-src-post:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push post service
        id: docker_build_post
        uses: docker/build-push-action@v2
        with:
          context: ./src/post
          file: ./src/post/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_POST }}
          cache-from: type=registry,ref=${{ env.IMAGE_SERVICE_POST }}:latest
          cache-to: type=inline