name: deploy-docker-get

on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/get/**'

env:
  IMAGE_SERVICE_GET: nugrohosam/go-kubectl-krakend-src-get:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push get service
        id: docker_build_get
        uses: docker/build-push-action@v2
        with:
          context: ./src/get
          file: ./src/get/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_GET }}
          cache-from: type=registry,ref=${{ env.IMAGE_SERVICE_GET }}:latest
          cache-to: type=inline