name: ci

on:
  push:
    branches:
      - 'master'

env:
  IMAGE_SERVICE_GATEWAY: nugrohosam/go-kubectl-krakend-src-gateway:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push gateway service
        id: docker_build_gateway
        uses: docker/build-push-action@v2
        with:
          context: ./src/gateway
          file: ./src/gateway/Dockerfile
          push: true
          tags: ${{ env.IMAGE_SERVICE_GATEWAY }}